file_format: "1"
id: charybdis_zmk
name: Charybdis_zmk
type: shield
url: https://github.com/Bastardkb/Charybdis/
requires: [pro_micro]
features:
  - keys
  - pointer
  - underglow
siblings:
  - charybdi_zmk_left
  - charybdis_zmk_right
